name: Tests Carte

on:
  push:      # à chaque push
    branches: [ main ]
  pull_request:  # aussi lors des PR

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances (s'il y en a)
        run: |
          python -m pip install --upgrade pip

      - name: Lancer les tests
        run: |
          python -m unittest discover -s . -p "test_*.py"
